#!/bin/bash

export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$UID/bus

if [ $1 -gt 0 ]
then
#  echo increasing by "$1" >> ~/bin/volumelog
 END=$1
 i=0
 while [[ $i -lt $END ]]
 do
    #echo $i >> ~/bin/brightnesslog
    qdbus org.kde.kmix /kmix/KMixWindow/actions/increase_volume org.qtproject.Qt.QAction.trigger
    ((i = i + 5))
 done
else
#  echo decreasing by "$1" >> ~/bin/volumelog
 END=$1
 i=0
 while [[ $i -gt $END ]]
 do
    #echo $i >> ~/bin/brightnesslog
    qdbus org.kde.kmix /kmix/KMixWindow/actions/decrease_volume org.qtproject.Qt.QAction.trigger
    ((i = i - 5))
 done
fi
